mod block_info_viewer;
mod coeffs_viewer;
mod controls_viewer;
mod decode_progress_viewer;
mod detailed_pixel_viewer;
mod drag_and_drop;
mod frame_info_viewer;
mod frame_select_viewer;
mod frame_viewer;
mod menu_bar;
mod performance_viewer;
mod render_view;
mod settings_viewer;
mod stats_viewer;
mod stream_select_viewer;
mod symbol_info_viewer;
mod view_mode;

pub use block_info_viewer::BlockInfoViewer;
pub use coeffs_viewer::CoeffsViewer;
pub use controls_viewer::ControlsViewer;
pub use decode_progress_viewer::DecodeProgressViewer;
pub use detailed_pixel_viewer::DetailedPixelViewer;
pub use drag_and_drop::handle_drag_and_drop;
pub use frame_info_viewer::FrameInfoViewer;
pub use frame_select_viewer::FrameSelectViewer;
pub use frame_viewer::{FrameViewer, ScreenBounds, SelectedObject, SelectedObjectKind};
pub use menu_bar::MenuBar;
pub use performance_viewer::{PerformanceHistory, PerformanceViewer};
pub use render_view::RenderView;
pub use settings_viewer::SettingsViewer;
pub use stats_viewer::StatsViewer;
pub use stream_select_viewer::StreamSelectViewer;
pub use symbol_info_viewer::SymbolInfoViewer;
pub use view_mode::ViewMode;

pub const MIN_BLOCK_SIZE_TO_RENDER: f32 = 2.0;
pub const MIN_BLOCK_HEIGHT_FOR_TEXT: f32 = 12.0;
pub const MIN_BLOCK_WIDTH_FOR_TEXT: f32 = 30.0;
